### ISSUE TITLE
Config type definitions require the use of an enum

### ISSUE THREAD

**Issue by G-Rath** [bmish/eslint-doc-generator#321]
[By using enums for certain properties in the config](https://github.com/bmish/eslint-doc-generator/pull/300), TypeScript requires us to actually use those enums - this is problematic because the tool is being shipped as ESM so configs have to be using ESM too i.e.

```
const { COLUMN_TYPE } = require('eslint-doc-generator/dist/lib/types');

/** @type {import('eslint-doc-generator').GenerateOptions} */
const config = {
  ignoreConfig: ['all'],
  ruleDocTitleFormat: 'desc-parens-name',
  ruleDocSectionInclude: ['Rule details'],
  ruleListColumns: [
    COLUMN_TYPE.NAME,
    COLUMN_TYPE.DESCRIPTION,
    COLUMN_TYPE.CONFIGS_ERROR,
    COLUMN_TYPE.CONFIGS_WARN,
    COLUMN_TYPE.CONFIGS_OFF,
    COLUMN_TYPE.FIXABLE,
    COLUMN_TYPE.HAS_SUGGESTIONS,
    COLUMN_TYPE.DEPRECATED,
  ],
  ruleListSplit: 'meta.docs.requiresTypeChecking',
  urlConfigs: `https://github.com/jest-community/eslint-plugin-jest/blob/main/README.md#shareable-configurations`,
};

module.exports = config;
```

results in:

```
eslint-plugin-jest on  renovate/eslint-doc-generator-1.x [$!?] is 📦 v27.1.6 via  v16.15.0 took 12s
❯ nrun tools:regenerate-docs
> nrun.js tools:regenerate-docs
> yarn prepack && eslint-doc-generator && yarn prettier:write
Successfully compiled 115 files with Babel (1552ms).
/home/gareth/workspace/projects-oss/eslint-plugin-jest/.eslint-doc-generatorrc.js:1
const { COLUMN_TYPE } = require('eslint-doc-generator/dist/lib/types');
                        ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/dist/lib/types.js from /home/gareth/workspace/projects-oss/eslint-plugin-jest/.eslint-doc-generatorrc.js not supported.
Instead change the require of types.js in /home/gareth/workspace/projects-oss/eslint-plugin-jest/.eslint-doc-generatorrc.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/gareth/workspace/projects-oss/eslint-plugin-jest/.eslint-doc-generatorrc.js:1:25)
    at module.exports (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/import-fresh/index.js:32:59)
    at loadJs (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/loaders.js:16:18)
    at Explorer.loadFileContent (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/Explorer.js:86:20)
    at Explorer.createCosmiconfigResult (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/Explorer.js:94:36)
    at Explorer.loadSearchPlace (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/Explorer.js:70:31)
    at async Explorer.searchDirectory (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/Explorer.js:55:27)
    at async run (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/Explorer.js:35:22)
    at async cacheWrapper (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async Explorer.search (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/node_modules/cosmiconfig/dist/Explorer.js:27:20)
    at async loadConfigFileOptions (file:///home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/dist/lib/cli.js:39:29)
    at async Command.<anonymous> (file:///home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/dist/lib/cli.js:149:35)
    at async Command.parseAsync (/home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/commander/lib/command.js:916:5)
    at async run (file:///home/gareth/workspace/projects-oss/eslint-plugin-jest/node_modules/eslint-doc-generator/dist/lib/cli.js:125:5) {
  code: 'ERR_REQUIRE_ESM',
  filepath: '/home/gareth/workspace/projects-oss/eslint-plugin-jest/.eslint-doc-generatorrc.js'
}
```

**Comment by bmish** [comment]
Won't exporting those enums publicly solve this?

**Comment by G-Rath** [comment]
Yes, string unions

**Comment by bmish** [comment]
@G-Rath I believe I have a good solution with string unions in #322.
